name: Build and deploy JAR app to Azure Web App - rahulpannati

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Java version
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Step 3: Build the project with Maven (skip tests for faster build)
      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests

<<<<<<< HEAD
      # Step 4: Upload artifact for deployment job
=======
      - name: List contents of target directory
        run: ls -al target/  # Verify if the JAR file is being generated correctly

>>>>>>> 146c0eb (vvjjd)
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      # Step 1: Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

<<<<<<< HEAD
      # Step 2: Login to Azure using the Service Principal
=======
      - name: List contents of downloaded artifact
        run: ls -al ${{ github.workspace }}/java-app/  # Verify if the JAR file is downloaded correctly

>>>>>>> 146c0eb (vvjjd)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Step 3: Set the Azure subscription to use
      - name: Set Azure Subscription
        run: |
          az account set --subscription ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Step 4: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
<<<<<<< HEAD
          app-name: 'rahulpannati'  # Ensure this is the correct Azure Web App name
          slot-name: 'Production'
          package: 'target/*.jar'  # Path to your built JAR file (ensure it matches the build output)

      # Optional: Post-deployment success URL (can be used to get the webapp URL after deployment)
      - name: Output Web App URL
        run: echo "Web App URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
=======
          app-name: 'spring-Ai'  # Ensure this is the correct Azure Web App name
          slot-name: 'Production'
          package: '${{ github.workspace }}/java-app/*.jar'  # Ensure correct path to JAR file
>>>>>>> 146c0eb (vvjjd)
