name: Build and deploy JAR app to Azure Web App - rahulpannati

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests  # Skip tests during the build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5519ACFF69114A2AB3060055DF9E171E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D4740665666742338C1C8EF6A1D13BAB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2490560585CE40CA82BB289416EC27A1 }}

      - name: Set Azure Subscription
        run: |
          az account set --subscription ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2490560585CE40CA82BB289416EC27A1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rahulpannati'  # Ensure this is the correct Azure Web App name
          slot-name: 'Production'
          package: 'target/*.jar'  # Specify the correct path to the JAR file
